### ISSUE TITLE
isorespin.sh isn't in github

### ISSUE THREAD

**Issue by qhartman** [stockmind/dell-xps-9560-ubuntu-respin#44]
The script that does most of the lifting isn't hosted here, but gets downloaded by build.sh at runtime. That seems clunky. Why not host it here with everything else? If it's just a case of history and there's not really a reason for it, I'm happy to build a PR that bakes it in here and changes build.sh to accommodate.

**Comment by qhartman** [comment]
Here's the PR - https://github.com/stockmind/dell-xps-9560-ubuntu-respin/pull/45

It was simple enough I decided to just go.... :smiley:

**Comment by stockmind** [comment]
Thanks for your PR! But the isorespin script is not mine, i don't own that script and i'm not a maintainer, so i choose to download it at runtime instead of packaging it with the repository, so a fresh cloned repository/or deleting it will always download the latest version from the official author link!

Here is the author blog: http://linuxiumcomau.blogspot.com/

I don't feel right including his work without a strong reason, as internet is required for a respin so is just an http request

If Ian will stop to provide his script from that link or something change i will be ok to merge it!

**Comment by qhartman** [comment]
Well, the biggest reason I can see for forking it into here would be make sure that what you've built continues to work for people, even if that goes away, or he makes some incompatible changes. It best conforms to the maxim of "least surprise". I would think that a note somewhere, in the comments or the readme with credit and the original URL and date of import would be sufficient to give credit and whatnot. I agree though that this is pretty much a judgement call. If you keep it as is, a note in the comments of what you're grabbing there and why would be good. When I found that it I was concerned since I wasn't expecting to be grabbing something from a third party as part of the process.

**Comment by stockmind** [comment]
> Well, the biggest reason I can see for forking it into here would be make sure that what you've built continues to work for people, even if that goes away, or he makes some incompatible changes. It best conforms to the maxim of "least surprise". 
You're right, i've always hesitated a bit due to this, as you said, if we have a working version we are sure that builds will always work.

I've better checked the license and will merge your changes, there is no strong reason to keep it out either from this repository, i was probably creating a problem where there is not.

Thank you for the arguments! :)

**Comment by qhartman** [comment]
Sure thing! And thanks for putting this together.
